spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/sql-police
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximumPoolSize: 10

  liquibase:
    enabled: true
    change-log: classpath:/db-changelog.yaml

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.batch_size: 500
        order_inserts: true
        order_updates: true
        batch_versioned_data: true


server:
  port: 8080
  servlet:
    context-path: /